package generate

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/StephenButtolph/canoto"
)

const (
	defaultCanotoSelector                = "canoto"
	libraryFileName                      = "canoto.go"
	generatedLibraryFileName             = "canoto.canoto.go"
	readWrite                            = 0o640
	readWriteExecute         os.FileMode = 0o750
)

// Library generates the canoto serialization primitives package in the provided
// folder.
//
// Specifically, if "./internal" is provided, this will generate the package
// "./internal/canoto" with the serialization primitives included in
// "./internal/canoto/canoto.go".
func Library(parentDir string) error {
	library := filepath.Join(parentDir, defaultCanotoSelector)
	if err := os.MkdirAll(library, readWriteExecute); err != nil {
		return fmt.Errorf("failed to create directory %q: %w", library, err)
	}

	var (
		libraryPath          = filepath.Join(library, libraryFileName)
		generatedLibraryPath = filepath.Join(library, generatedLibraryFileName)
	)

	doNotGenerate := fmt.Sprintf(
		`// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto %s

`,
		canoto.Version,
	)
	if err := os.WriteFile(libraryPath, []byte(doNotGenerate+canoto.Code), readWrite); err != nil {
		return fmt.Errorf("failed to write file %q: %w", libraryPath, err)
	}
	if err := os.WriteFile(generatedLibraryPath, []byte(canoto.GeneratedCode), readWrite); err != nil {
		return fmt.Errorf("failed to write file %q: %w", libraryPath, err)
	}
	return nil
}
