// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.18.1
// source: canoto.go

package canoto

import (
	"io"
	"reflect"
	"sync/atomic"
)

// Ensure that the generated code is compatible with the library version.
const (
	_ uint = VersionCompatibility - 1
	_ uint = 1 - VersionCompatibility
)

// Ensure that unused imports do not error
var _ = io.ErrUnexpectedEOF

const (
	canotoNumber_Spec__Name   = 1
	canotoNumber_Spec__Fields = 2

	canotoTag_Spec__Name   = "\x0a" // canoto.Tag(canotoNumber_Spec__Name, canoto.Len)
	canotoTag_Spec__Fields = "\x12" // canoto.Tag(canotoNumber_Spec__Fields, canoto.Len)
)

type canotoData_Spec struct {
	size uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*Spec) CanotoSpec(types ...reflect.Type) *Spec {
	types = append(types, reflect.TypeFor[Spec]())
	var zero Spec
	s := &Spec{
		Name: "Spec",
		Fields: []FieldType{
			{
				FieldNumber: canotoNumber_Spec__Name,
				Name:        "Name",
				OneOf:       "",
				TypeString:  true,
			},
			FieldTypeFromField(
				/*type inference:*/ (MakeEntryNilPointer(zero.Fields)),
				/*FieldNumber:   */ canotoNumber_Spec__Fields,
				/*Name:          */ "Fields",
				/*FixedLength:   */ 0,
				/*Repeated:      */ true,
				/*OneOf:         */ "",
				/*Pointer:       */ false,
				/*types:         */ types,
			),
		},
	}
	s.CalculateCanotoCache()
	return s
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *Spec) UnmarshalCanoto(bytes []byte) error {
	r := Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *Spec) UnmarshalCanotoFrom(r Reader) error {
	// Zero the struct before unmarshaling.
	*c = Spec{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for HasNext(&r) {
		field, wireType, err := ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return ErrInvalidFieldOrder
		}

		switch field {
		case canotoNumber_Spec__Name:
			if wireType != Len {
				return ErrUnexpectedWireType
			}

			if err := ReadString(&r, &c.Name); err != nil {
				return err
			}
			if len(c.Name) == 0 {
				return ErrZeroValue
			}
		case canotoNumber_Spec__Fields:
			if wireType != Len {
				return ErrUnexpectedWireType
			}

			// Read the first entry manually because the tag is already
			// stripped.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			// Count the number of additional entries after the first entry.
			countMinus1, err := CountBytes(r.B, canotoTag_Spec__Fields)
			if err != nil {
				return err
			}

			c.Fields = MakeSlice(c.Fields, countMinus1+1)
			field := c.Fields
			additionalField := field[1:]
			if len(msgBytes) != 0 {
				remainingBytes := r.B
				r.B = msgBytes
				if err := (&field[0]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}

			// Read the rest of the entries, stripping the tag each time.
			for i := range additionalField {
				r.B = r.B[len(canotoTag_Spec__Fields):]
				r.Unsafe = true
				if err := ReadBytes(&r, &msgBytes); err != nil {
					return err
				}
				r.Unsafe = originalUnsafe
				if len(msgBytes) == 0 {
					continue
				}

				remainingBytes := r.B
				r.B = msgBytes
				if err := (&additionalField[i]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}
		default:
			return ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *Spec) ValidCanoto() bool {
	if !ValidString(c.Name) {
		return false
	}
	{
		field := c.Fields
		for i := range field {
			if !(&field[i]).ValidCanoto() {
				return false
			}
		}
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *Spec) CalculateCanotoCache() {
	var size uint64
	if len(c.Name) != 0 {
		size += uint64(len(canotoTag_Spec__Name)) + SizeBytes(c.Name)
	}
	{
		field := c.Fields
		for i := range field {
			(&field[i]).CalculateCanotoCache()
			fieldSize := (&field[i]).CachedCanotoSize()
			size += uint64(len(canotoTag_Spec__Fields)) + SizeUint(fieldSize) + fieldSize
		}
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *Spec) CachedCanotoSize() uint64 {
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *Spec) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [Writer] and returns the
// resulting [Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *Spec) MarshalCanotoInto(w Writer) Writer {
	if len(c.Name) != 0 {
		Append(&w, canotoTag_Spec__Name)
		AppendBytes(&w, c.Name)
	}
	{
		field := c.Fields
		for i := range field {
			Append(&w, canotoTag_Spec__Fields)
			AppendUint(&w, (&field[i]).CachedCanotoSize())
			w = (&field[i]).MarshalCanotoInto(w)
		}
	}
	return w
}

const (
	canotoNumber_FieldType__FieldNumber    = 1
	canotoNumber_FieldType__Name           = 2
	canotoNumber_FieldType__FixedLength    = 3
	canotoNumber_FieldType__Repeated       = 4
	canotoNumber_FieldType__OneOf          = 5
	canotoNumber_FieldType__Pointer        = 6
	canotoNumber_FieldType__TypeInt        = 7
	canotoNumber_FieldType__TypeUint       = 8
	canotoNumber_FieldType__TypeFixedInt   = 9
	canotoNumber_FieldType__TypeFixedUint  = 10
	canotoNumber_FieldType__TypeBool       = 11
	canotoNumber_FieldType__TypeString     = 12
	canotoNumber_FieldType__TypeBytes      = 13
	canotoNumber_FieldType__TypeFixedBytes = 14
	canotoNumber_FieldType__TypeMessage    = 15
	canotoNumber_FieldType__TypeRecursive  = 16

	canotoTag_FieldType__FieldNumber    = "\x08"     // canoto.Tag(canotoNumber_FieldType__FieldNumber, canoto.Varint)
	canotoTag_FieldType__Name           = "\x12"     // canoto.Tag(canotoNumber_FieldType__Name, canoto.Len)
	canotoTag_FieldType__FixedLength    = "\x18"     // canoto.Tag(canotoNumber_FieldType__FixedLength, canoto.Varint)
	canotoTag_FieldType__Repeated       = "\x20"     // canoto.Tag(canotoNumber_FieldType__Repeated, canoto.Varint)
	canotoTag_FieldType__OneOf          = "\x2a"     // canoto.Tag(canotoNumber_FieldType__OneOf, canoto.Len)
	canotoTag_FieldType__Pointer        = "\x30"     // canoto.Tag(canotoNumber_FieldType__Pointer, canoto.Varint)
	canotoTag_FieldType__TypeInt        = "\x38"     // canoto.Tag(canotoNumber_FieldType__TypeInt, canoto.Varint)
	canotoTag_FieldType__TypeUint       = "\x40"     // canoto.Tag(canotoNumber_FieldType__TypeUint, canoto.Varint)
	canotoTag_FieldType__TypeFixedInt   = "\x48"     // canoto.Tag(canotoNumber_FieldType__TypeFixedInt, canoto.Varint)
	canotoTag_FieldType__TypeFixedUint  = "\x50"     // canoto.Tag(canotoNumber_FieldType__TypeFixedUint, canoto.Varint)
	canotoTag_FieldType__TypeBool       = "\x58"     // canoto.Tag(canotoNumber_FieldType__TypeBool, canoto.Varint)
	canotoTag_FieldType__TypeString     = "\x60"     // canoto.Tag(canotoNumber_FieldType__TypeString, canoto.Varint)
	canotoTag_FieldType__TypeBytes      = "\x68"     // canoto.Tag(canotoNumber_FieldType__TypeBytes, canoto.Varint)
	canotoTag_FieldType__TypeFixedBytes = "\x70"     // canoto.Tag(canotoNumber_FieldType__TypeFixedBytes, canoto.Varint)
	canotoTag_FieldType__TypeMessage    = "\x7a"     // canoto.Tag(canotoNumber_FieldType__TypeMessage, canoto.Len)
	canotoTag_FieldType__TypeRecursive  = "\x80\x01" // canoto.Tag(canotoNumber_FieldType__TypeRecursive, canoto.Varint)
)

// canotoOneOfType_FieldType__Type identifies which field is populated in Type.
type canotoOneOfType_FieldType__Type uint32

const (
	canotoOneOfUnset_FieldType__Type      canotoOneOfType_FieldType__Type = 0
	canotoOneOf_FieldType__TypeInt        canotoOneOfType_FieldType__Type = canotoNumber_FieldType__TypeInt
	canotoOneOf_FieldType__TypeUint       canotoOneOfType_FieldType__Type = canotoNumber_FieldType__TypeUint
	canotoOneOf_FieldType__TypeFixedInt   canotoOneOfType_FieldType__Type = canotoNumber_FieldType__TypeFixedInt
	canotoOneOf_FieldType__TypeFixedUint  canotoOneOfType_FieldType__Type = canotoNumber_FieldType__TypeFixedUint
	canotoOneOf_FieldType__TypeBool       canotoOneOfType_FieldType__Type = canotoNumber_FieldType__TypeBool
	canotoOneOf_FieldType__TypeString     canotoOneOfType_FieldType__Type = canotoNumber_FieldType__TypeString
	canotoOneOf_FieldType__TypeBytes      canotoOneOfType_FieldType__Type = canotoNumber_FieldType__TypeBytes
	canotoOneOf_FieldType__TypeFixedBytes canotoOneOfType_FieldType__Type = canotoNumber_FieldType__TypeFixedBytes
	canotoOneOf_FieldType__TypeMessage    canotoOneOfType_FieldType__Type = canotoNumber_FieldType__TypeMessage
	canotoOneOf_FieldType__TypeRecursive  canotoOneOfType_FieldType__Type = canotoNumber_FieldType__TypeRecursive
)

type canotoData_FieldType struct {
	size uint64

	TypeOneOf uint32
}

// CanotoSpec returns the specification of this canoto message.
func (*FieldType) CanotoSpec(types ...reflect.Type) *Spec {
	types = append(types, reflect.TypeFor[FieldType]())
	var zero FieldType
	s := &Spec{
		Name: "FieldType",
		Fields: []FieldType{
			{
				FieldNumber: canotoNumber_FieldType__FieldNumber,
				Name:        "FieldNumber",
				OneOf:       "",
				TypeUint:    SizeOf(zero.FieldNumber),
			},
			{
				FieldNumber: canotoNumber_FieldType__Name,
				Name:        "Name",
				OneOf:       "",
				TypeString:  true,
			},
			{
				FieldNumber: canotoNumber_FieldType__FixedLength,
				Name:        "FixedLength",
				OneOf:       "",
				TypeUint:    SizeOf(zero.FixedLength),
			},
			{
				FieldNumber: canotoNumber_FieldType__Repeated,
				Name:        "Repeated",
				OneOf:       "",
				TypeBool:    true,
			},
			{
				FieldNumber: canotoNumber_FieldType__OneOf,
				Name:        "OneOf",
				OneOf:       "",
				TypeString:  true,
			},
			{
				FieldNumber: canotoNumber_FieldType__Pointer,
				Name:        "Pointer",
				OneOf:       "",
				TypeBool:    true,
			},
			{
				FieldNumber: canotoNumber_FieldType__TypeInt,
				Name:        "TypeInt",
				OneOf:       "Type",
				TypeUint:    SizeOf(zero.TypeInt),
			},
			{
				FieldNumber: canotoNumber_FieldType__TypeUint,
				Name:        "TypeUint",
				OneOf:       "Type",
				TypeUint:    SizeOf(zero.TypeUint),
			},
			{
				FieldNumber: canotoNumber_FieldType__TypeFixedInt,
				Name:        "TypeFixedInt",
				OneOf:       "Type",
				TypeUint:    SizeOf(zero.TypeFixedInt),
			},
			{
				FieldNumber: canotoNumber_FieldType__TypeFixedUint,
				Name:        "TypeFixedUint",
				OneOf:       "Type",
				TypeUint:    SizeOf(zero.TypeFixedUint),
			},
			{
				FieldNumber: canotoNumber_FieldType__TypeBool,
				Name:        "TypeBool",
				OneOf:       "Type",
				TypeBool:    true,
			},
			{
				FieldNumber: canotoNumber_FieldType__TypeString,
				Name:        "TypeString",
				OneOf:       "Type",
				TypeBool:    true,
			},
			{
				FieldNumber: canotoNumber_FieldType__TypeBytes,
				Name:        "TypeBytes",
				OneOf:       "Type",
				TypeBool:    true,
			},
			{
				FieldNumber: canotoNumber_FieldType__TypeFixedBytes,
				Name:        "TypeFixedBytes",
				OneOf:       "Type",
				TypeUint:    SizeOf(zero.TypeFixedBytes),
			},
			FieldTypeFromField(
				/*type inference:*/ (zero.TypeMessage),
				/*FieldNumber:   */ canotoNumber_FieldType__TypeMessage,
				/*Name:          */ "TypeMessage",
				/*FixedLength:   */ 0,
				/*Repeated:      */ false,
				/*OneOf:         */ "Type",
				/*Pointer:       */ true,
				/*types:         */ types,
			),
			{
				FieldNumber: canotoNumber_FieldType__TypeRecursive,
				Name:        "TypeRecursive",
				OneOf:       "Type",
				TypeUint:    SizeOf(zero.TypeRecursive),
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *FieldType) UnmarshalCanoto(bytes []byte) error {
	r := Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *FieldType) UnmarshalCanotoFrom(r Reader) error {
	// Zero the struct before unmarshaling.
	*c = FieldType{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for HasNext(&r) {
		field, wireType, err := ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return ErrInvalidFieldOrder
		}

		switch field {
		case canotoNumber_FieldType__FieldNumber:
			if wireType != Varint {
				return ErrUnexpectedWireType
			}

			if err := ReadUint(&r, &c.FieldNumber); err != nil {
				return err
			}
			if IsZero(c.FieldNumber) {
				return ErrZeroValue
			}
		case canotoNumber_FieldType__Name:
			if wireType != Len {
				return ErrUnexpectedWireType
			}

			if err := ReadString(&r, &c.Name); err != nil {
				return err
			}
			if len(c.Name) == 0 {
				return ErrZeroValue
			}
		case canotoNumber_FieldType__FixedLength:
			if wireType != Varint {
				return ErrUnexpectedWireType
			}

			if err := ReadUint(&r, &c.FixedLength); err != nil {
				return err
			}
			if IsZero(c.FixedLength) {
				return ErrZeroValue
			}
		case canotoNumber_FieldType__Repeated:
			if wireType != Varint {
				return ErrUnexpectedWireType
			}

			if err := ReadBool(&r, &c.Repeated); err != nil {
				return err
			}
			if IsZero(c.Repeated) {
				return ErrZeroValue
			}
		case canotoNumber_FieldType__OneOf:
			if wireType != Len {
				return ErrUnexpectedWireType
			}

			if err := ReadString(&r, &c.OneOf); err != nil {
				return err
			}
			if len(c.OneOf) == 0 {
				return ErrZeroValue
			}
		case canotoNumber_FieldType__Pointer:
			if wireType != Varint {
				return ErrUnexpectedWireType
			}

			if err := ReadBool(&r, &c.Pointer); err != nil {
				return err
			}
			if IsZero(c.Pointer) {
				return ErrZeroValue
			}
		case canotoNumber_FieldType__TypeInt:
			if wireType != Varint {
				return ErrUnexpectedWireType
			}
			if atomic.SwapUint32(&c.canotoData.TypeOneOf, canotoNumber_FieldType__TypeInt) != 0 {
				return ErrDuplicateOneOf
			}

			if err := ReadUint(&r, &c.TypeInt); err != nil {
				return err
			}
			if IsZero(c.TypeInt) {
				return ErrZeroValue
			}
		case canotoNumber_FieldType__TypeUint:
			if wireType != Varint {
				return ErrUnexpectedWireType
			}
			if atomic.SwapUint32(&c.canotoData.TypeOneOf, canotoNumber_FieldType__TypeUint) != 0 {
				return ErrDuplicateOneOf
			}

			if err := ReadUint(&r, &c.TypeUint); err != nil {
				return err
			}
			if IsZero(c.TypeUint) {
				return ErrZeroValue
			}
		case canotoNumber_FieldType__TypeFixedInt:
			if wireType != Varint {
				return ErrUnexpectedWireType
			}
			if atomic.SwapUint32(&c.canotoData.TypeOneOf, canotoNumber_FieldType__TypeFixedInt) != 0 {
				return ErrDuplicateOneOf
			}

			if err := ReadUint(&r, &c.TypeFixedInt); err != nil {
				return err
			}
			if IsZero(c.TypeFixedInt) {
				return ErrZeroValue
			}
		case canotoNumber_FieldType__TypeFixedUint:
			if wireType != Varint {
				return ErrUnexpectedWireType
			}
			if atomic.SwapUint32(&c.canotoData.TypeOneOf, canotoNumber_FieldType__TypeFixedUint) != 0 {
				return ErrDuplicateOneOf
			}

			if err := ReadUint(&r, &c.TypeFixedUint); err != nil {
				return err
			}
			if IsZero(c.TypeFixedUint) {
				return ErrZeroValue
			}
		case canotoNumber_FieldType__TypeBool:
			if wireType != Varint {
				return ErrUnexpectedWireType
			}
			if atomic.SwapUint32(&c.canotoData.TypeOneOf, canotoNumber_FieldType__TypeBool) != 0 {
				return ErrDuplicateOneOf
			}

			if err := ReadBool(&r, &c.TypeBool); err != nil {
				return err
			}
			if IsZero(c.TypeBool) {
				return ErrZeroValue
			}
		case canotoNumber_FieldType__TypeString:
			if wireType != Varint {
				return ErrUnexpectedWireType
			}
			if atomic.SwapUint32(&c.canotoData.TypeOneOf, canotoNumber_FieldType__TypeString) != 0 {
				return ErrDuplicateOneOf
			}

			if err := ReadBool(&r, &c.TypeString); err != nil {
				return err
			}
			if IsZero(c.TypeString) {
				return ErrZeroValue
			}
		case canotoNumber_FieldType__TypeBytes:
			if wireType != Varint {
				return ErrUnexpectedWireType
			}
			if atomic.SwapUint32(&c.canotoData.TypeOneOf, canotoNumber_FieldType__TypeBytes) != 0 {
				return ErrDuplicateOneOf
			}

			if err := ReadBool(&r, &c.TypeBytes); err != nil {
				return err
			}
			if IsZero(c.TypeBytes) {
				return ErrZeroValue
			}
		case canotoNumber_FieldType__TypeFixedBytes:
			if wireType != Varint {
				return ErrUnexpectedWireType
			}
			if atomic.SwapUint32(&c.canotoData.TypeOneOf, canotoNumber_FieldType__TypeFixedBytes) != 0 {
				return ErrDuplicateOneOf
			}

			if err := ReadUint(&r, &c.TypeFixedBytes); err != nil {
				return err
			}
			if IsZero(c.TypeFixedBytes) {
				return ErrZeroValue
			}
		case canotoNumber_FieldType__TypeMessage:
			if wireType != Len {
				return ErrUnexpectedWireType
			}
			if atomic.SwapUint32(&c.canotoData.TypeOneOf, canotoNumber_FieldType__TypeMessage) != 0 {
				return ErrDuplicateOneOf
			}

			// Read the bytes for the field.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			// Unmarshal the field from the bytes.
			remainingBytes := r.B
			r.B = msgBytes
			c.TypeMessage = MakePointer(c.TypeMessage)
			if err := (c.TypeMessage).UnmarshalCanotoFrom(r); err != nil {
				return err
			}
			r.B = remainingBytes
		case canotoNumber_FieldType__TypeRecursive:
			if wireType != Varint {
				return ErrUnexpectedWireType
			}
			if atomic.SwapUint32(&c.canotoData.TypeOneOf, canotoNumber_FieldType__TypeRecursive) != 0 {
				return ErrDuplicateOneOf
			}

			if err := ReadUint(&r, &c.TypeRecursive); err != nil {
				return err
			}
			if IsZero(c.TypeRecursive) {
				return ErrZeroValue
			}
		default:
			return ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *FieldType) ValidCanoto() bool {
	var TypeOneOf uint32
	if !IsZero(c.TypeInt) {
		if TypeOneOf != 0 {
			return false
		}
		TypeOneOf = canotoNumber_FieldType__TypeInt
	}
	if !IsZero(c.TypeUint) {
		if TypeOneOf != 0 {
			return false
		}
		TypeOneOf = canotoNumber_FieldType__TypeUint
	}
	if !IsZero(c.TypeFixedInt) {
		if TypeOneOf != 0 {
			return false
		}
		TypeOneOf = canotoNumber_FieldType__TypeFixedInt
	}
	if !IsZero(c.TypeFixedUint) {
		if TypeOneOf != 0 {
			return false
		}
		TypeOneOf = canotoNumber_FieldType__TypeFixedUint
	}
	if !IsZero(c.TypeBool) {
		if TypeOneOf != 0 {
			return false
		}
		TypeOneOf = canotoNumber_FieldType__TypeBool
	}
	if !IsZero(c.TypeString) {
		if TypeOneOf != 0 {
			return false
		}
		TypeOneOf = canotoNumber_FieldType__TypeString
	}
	if !IsZero(c.TypeBytes) {
		if TypeOneOf != 0 {
			return false
		}
		TypeOneOf = canotoNumber_FieldType__TypeBytes
	}
	if !IsZero(c.TypeFixedBytes) {
		if TypeOneOf != 0 {
			return false
		}
		TypeOneOf = canotoNumber_FieldType__TypeFixedBytes
	}
	if c.TypeMessage != nil {
		(c.TypeMessage).CalculateCanotoCache()
		if TypeOneOf != 0 {
			return false
		}
		TypeOneOf = canotoNumber_FieldType__TypeMessage
	}
	if !IsZero(c.TypeRecursive) {
		if TypeOneOf != 0 {
			return false
		}
		TypeOneOf = canotoNumber_FieldType__TypeRecursive
	}
	if !ValidString(c.Name) {
		return false
	}
	if !ValidString(c.OneOf) {
		return false
	}
	if c.TypeMessage != nil && !(c.TypeMessage).ValidCanoto() {
		return false
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *FieldType) CalculateCanotoCache() {
	var size uint64
	var TypeOneOf uint32
	if !IsZero(c.FieldNumber) {
		size += uint64(len(canotoTag_FieldType__FieldNumber)) + SizeUint(c.FieldNumber)
	}
	if len(c.Name) != 0 {
		size += uint64(len(canotoTag_FieldType__Name)) + SizeBytes(c.Name)
	}
	if !IsZero(c.FixedLength) {
		size += uint64(len(canotoTag_FieldType__FixedLength)) + SizeUint(c.FixedLength)
	}
	if !IsZero(c.Repeated) {
		size += uint64(len(canotoTag_FieldType__Repeated)) + SizeBool
	}
	if len(c.OneOf) != 0 {
		size += uint64(len(canotoTag_FieldType__OneOf)) + SizeBytes(c.OneOf)
	}
	if !IsZero(c.Pointer) {
		size += uint64(len(canotoTag_FieldType__Pointer)) + SizeBool
	}
	if !IsZero(c.TypeInt) {
		size += uint64(len(canotoTag_FieldType__TypeInt)) + SizeUint(c.TypeInt)
		TypeOneOf = canotoNumber_FieldType__TypeInt
	}
	if !IsZero(c.TypeUint) {
		size += uint64(len(canotoTag_FieldType__TypeUint)) + SizeUint(c.TypeUint)
		TypeOneOf = canotoNumber_FieldType__TypeUint
	}
	if !IsZero(c.TypeFixedInt) {
		size += uint64(len(canotoTag_FieldType__TypeFixedInt)) + SizeUint(c.TypeFixedInt)
		TypeOneOf = canotoNumber_FieldType__TypeFixedInt
	}
	if !IsZero(c.TypeFixedUint) {
		size += uint64(len(canotoTag_FieldType__TypeFixedUint)) + SizeUint(c.TypeFixedUint)
		TypeOneOf = canotoNumber_FieldType__TypeFixedUint
	}
	if !IsZero(c.TypeBool) {
		size += uint64(len(canotoTag_FieldType__TypeBool)) + SizeBool
		TypeOneOf = canotoNumber_FieldType__TypeBool
	}
	if !IsZero(c.TypeString) {
		size += uint64(len(canotoTag_FieldType__TypeString)) + SizeBool
		TypeOneOf = canotoNumber_FieldType__TypeString
	}
	if !IsZero(c.TypeBytes) {
		size += uint64(len(canotoTag_FieldType__TypeBytes)) + SizeBool
		TypeOneOf = canotoNumber_FieldType__TypeBytes
	}
	if !IsZero(c.TypeFixedBytes) {
		size += uint64(len(canotoTag_FieldType__TypeFixedBytes)) + SizeUint(c.TypeFixedBytes)
		TypeOneOf = canotoNumber_FieldType__TypeFixedBytes
	}
	if c.TypeMessage != nil {
		(c.TypeMessage).CalculateCanotoCache()
		fieldSize := (c.TypeMessage).CachedCanotoSize()
		size += uint64(len(canotoTag_FieldType__TypeMessage)) + SizeUint(fieldSize) + fieldSize
		TypeOneOf = canotoNumber_FieldType__TypeMessage
	}
	if !IsZero(c.TypeRecursive) {
		size += uint64(len(canotoTag_FieldType__TypeRecursive)) + SizeUint(c.TypeRecursive)
		TypeOneOf = canotoNumber_FieldType__TypeRecursive
	}
	atomic.StoreUint64(&c.canotoData.size, size)
	atomic.StoreUint32(&c.canotoData.TypeOneOf, TypeOneOf)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *FieldType) CachedCanotoSize() uint64 {
	return atomic.LoadUint64(&c.canotoData.size)
}

// CachedWhichOneOfType returns the previously calculated field number used
// to represent Type.
//
// This field is cached by UnmarshalCanoto, UnmarshalCanotoFrom, and
// CalculateCanotoCache.
//
// If the field has not yet been cached, it will return 0.
//
// If the struct has been modified since the field was last cached, the returned
// field number may be incorrect.
func (c *FieldType) CachedWhichOneOfType() uint32 {
	return (atomic.LoadUint32(&c.canotoData.TypeOneOf))
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *FieldType) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [Writer] and returns the
// resulting [Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *FieldType) MarshalCanotoInto(w Writer) Writer {
	if !IsZero(c.FieldNumber) {
		Append(&w, canotoTag_FieldType__FieldNumber)
		AppendUint(&w, c.FieldNumber)
	}
	if len(c.Name) != 0 {
		Append(&w, canotoTag_FieldType__Name)
		AppendBytes(&w, c.Name)
	}
	if !IsZero(c.FixedLength) {
		Append(&w, canotoTag_FieldType__FixedLength)
		AppendUint(&w, c.FixedLength)
	}
	if !IsZero(c.Repeated) {
		Append(&w, canotoTag_FieldType__Repeated)
		AppendBool(&w, true)
	}
	if len(c.OneOf) != 0 {
		Append(&w, canotoTag_FieldType__OneOf)
		AppendBytes(&w, c.OneOf)
	}
	if !IsZero(c.Pointer) {
		Append(&w, canotoTag_FieldType__Pointer)
		AppendBool(&w, true)
	}
	cachedWhichOneOfType := atomic.LoadUint32(&c.canotoData.TypeOneOf)
	switch cachedWhichOneOfType {
	case canotoNumber_FieldType__TypeInt:
		Append(&w, canotoTag_FieldType__TypeInt)
		AppendUint(&w, c.TypeInt)
	case canotoNumber_FieldType__TypeUint:
		Append(&w, canotoTag_FieldType__TypeUint)
		AppendUint(&w, c.TypeUint)
	case canotoNumber_FieldType__TypeFixedInt:
		Append(&w, canotoTag_FieldType__TypeFixedInt)
		AppendUint(&w, c.TypeFixedInt)
	case canotoNumber_FieldType__TypeFixedUint:
		Append(&w, canotoTag_FieldType__TypeFixedUint)
		AppendUint(&w, c.TypeFixedUint)
	case canotoNumber_FieldType__TypeBool:
		Append(&w, canotoTag_FieldType__TypeBool)
		AppendBool(&w, true)
	case canotoNumber_FieldType__TypeString:
		Append(&w, canotoTag_FieldType__TypeString)
		AppendBool(&w, true)
	case canotoNumber_FieldType__TypeBytes:
		Append(&w, canotoTag_FieldType__TypeBytes)
		AppendBool(&w, true)
	case canotoNumber_FieldType__TypeFixedBytes:
		Append(&w, canotoTag_FieldType__TypeFixedBytes)
		AppendUint(&w, c.TypeFixedBytes)
	case canotoNumber_FieldType__TypeMessage:
		fieldSize := (c.TypeMessage).CachedCanotoSize()
		Append(&w, canotoTag_FieldType__TypeMessage)
		AppendUint(&w, fieldSize)
		w = (c.TypeMessage).MarshalCanotoInto(w)
	case canotoNumber_FieldType__TypeRecursive:
		Append(&w, canotoTag_FieldType__TypeRecursive)
		AppendUint(&w, c.TypeRecursive)
	}
	return w
}
