// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.18.1
// source: custom_format.go

package examples

import (
	"io"
	"reflect"
	"sync/atomic"

	"github.com/StephenButtolph/canoto"
)

// Ensure that the generated code is compatible with the library version.
const (
	_ uint = canoto.VersionCompatibility - 1
	_ uint = 1 - canoto.VersionCompatibility
)

// Ensure that unused imports do not error
var _ = io.ErrUnexpectedEOF

const (
	CustomFormatANumber = 1
	CustomFormatBNumber = 2

	CustomFormatATag = "\x08" // canoto.Tag(CustomFormatANumber, canoto.Varint)
	CustomFormatBTag = "\x10" // canoto.Tag(CustomFormatBNumber, canoto.Varint)
)

// CustomFormatFields identifies which field is populated in Fields.
type CustomFormatFields uint32

const (
	CustomFormatFieldsUnset CustomFormatFields = 0
	CustomFormatFieldsA     CustomFormatFields = CustomFormatANumber
	CustomFormatFieldsB     CustomFormatFields = CustomFormatBNumber
)

type CustomFormatCache struct {
	size uint64

	FieldsOneOf uint32
}

// CanotoSpec returns the specification of this canoto message.
func (*CustomFormat) CanotoSpec(...reflect.Type) *canoto.Spec {
	var zero CustomFormat
	s := &canoto.Spec{
		Name: "CustomFormat",
		Fields: []canoto.FieldType{
			{
				FieldNumber: CustomFormatANumber,
				Name:        "A",
				OneOf:       "Fields",
				TypeUint:    canoto.SizeOf(zero.A),
			},
			{
				FieldNumber: CustomFormatBNumber,
				Name:        "B",
				OneOf:       "Fields",
				TypeUint:    canoto.SizeOf(zero.B),
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *CustomFormat) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *CustomFormat) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = CustomFormat{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case CustomFormatANumber:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}
			if atomic.SwapUint32(&c.canotoData.FieldsOneOf, CustomFormatANumber) != 0 {
				return canoto.ErrDuplicateOneOf
			}

			if err := canoto.ReadUint(&r, &c.A); err != nil {
				return err
			}
			if canoto.IsZero(c.A) {
				return canoto.ErrZeroValue
			}
		case CustomFormatBNumber:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}
			if atomic.SwapUint32(&c.canotoData.FieldsOneOf, CustomFormatBNumber) != 0 {
				return canoto.ErrDuplicateOneOf
			}

			if err := canoto.ReadUint(&r, &c.B); err != nil {
				return err
			}
			if canoto.IsZero(c.B) {
				return canoto.ErrZeroValue
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *CustomFormat) ValidCanoto() bool {
	var FieldsOneOf uint32
	if !canoto.IsZero(c.A) {
		if FieldsOneOf != 0 {
			return false
		}
		FieldsOneOf = CustomFormatANumber
	}
	if !canoto.IsZero(c.B) {
		if FieldsOneOf != 0 {
			return false
		}
		FieldsOneOf = CustomFormatBNumber
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *CustomFormat) CalculateCanotoCache() {
	var size uint64
	var FieldsOneOf uint32
	if !canoto.IsZero(c.A) {
		size += uint64(len(CustomFormatATag)) + canoto.SizeUint(c.A)
		FieldsOneOf = CustomFormatANumber
	}
	if !canoto.IsZero(c.B) {
		size += uint64(len(CustomFormatBTag)) + canoto.SizeUint(c.B)
		FieldsOneOf = CustomFormatBNumber
	}
	atomic.StoreUint64(&c.canotoData.size, size)
	atomic.StoreUint32(&c.canotoData.FieldsOneOf, FieldsOneOf)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *CustomFormat) CachedCanotoSize() uint64 {
	return atomic.LoadUint64(&c.canotoData.size)
}

// CachedWhichOneOfFields returns the previously calculated field number used
// to represent Fields.
//
// This field is cached by UnmarshalCanoto, UnmarshalCanotoFrom, and
// CalculateCanotoCache.
//
// If the field has not yet been cached, it will return CustomFormatFieldsUnset.
//
// If the struct has been modified since the field was last cached, the returned
// field number may be incorrect.
func (c *CustomFormat) CachedWhichOneOfFields() CustomFormatFields {
	return CustomFormatFields(atomic.LoadUint32(&c.canotoData.FieldsOneOf))
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *CustomFormat) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *CustomFormat) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	cachedWhichOneOfFields := atomic.LoadUint32(&c.canotoData.FieldsOneOf)
	switch cachedWhichOneOfFields {
	case CustomFormatANumber:
		canoto.Append(&w, CustomFormatATag)
		canoto.AppendUint(&w, c.A)
	case CustomFormatBNumber:
		canoto.Append(&w, CustomFormatBTag)
		canoto.AppendUint(&w, c.B)
	}
	return w
}
