// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.19.0
// source: inlined_canoto.go

package examples

import (
	"io"
	"reflect"
	"sync/atomic"

	"github.com/StephenButtolph/canoto/internal/canoto"
)

// Ensure that the generated code is compatible with the library version.
const (
	_ uint = canoto.VersionCompatibility - 1
	_ uint = 1 - canoto.VersionCompatibility
)

// Ensure that unused imports do not error
var _ = io.ErrUnexpectedEOF

const (
	canotoNumber_justAnInt__Int8 = 1

	canotoTag_justAnInt__Int8 = "\x08" // canoto.Tag(canotoNumber_justAnInt__Int8, canoto.Varint)
)

type canotoData_justAnInt struct {
	size atomic.Uint64
}

// CanotoSpec returns the specification of this canoto message, describing its
// fields and their wire types.
//
// types is used as a stack of ancestor messages to detect recursive specs.
//
// If there is not a valid specification of this type, it returns nil.
func (*justAnInt) CanotoSpec(...reflect.Type) *canoto.Spec {
	var zero justAnInt
	s := &canoto.Spec{
		Name: "justAnInt",
		Fields: []canoto.FieldType{
			{
				FieldNumber: canotoNumber_justAnInt__Int8,
				Name:        "Int8",
				OneOf:       "",
				TypeInt:     canoto.SizeOf(zero.Int8),
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *justAnInt) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *justAnInt) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = justAnInt{}
	c.canotoData.size.Store(uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case canotoNumber_justAnInt__Int8:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadInt(&r, &c.Int8); err != nil {
				return err
			}
			if canoto.IsZero(c.Int8) {
				return canoto.ErrZeroValue
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
//
//  1. All OneOfs are specified at most once.
//  2. All strings are valid utf-8.
//  3. All custom fields are ValidCanoto.
func (c *justAnInt) ValidCanoto() bool {
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
func (c *justAnInt) CalculateCanotoCache() {
	var size uint64
	if !canoto.IsZero(c.Int8) {
		size += uint64(len(canotoTag_justAnInt__Int8)) + canoto.SizeInt(c.Int8)
	}
	c.canotoData.size.Store(size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *justAnInt) CachedCanotoSize() uint64 {
	return c.canotoData.size.Load()
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
func (c *justAnInt) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
func (c *justAnInt) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if !canoto.IsZero(c.Int8) {
		canoto.Append(&w, canotoTag_justAnInt__Int8)
		canoto.AppendInt(&w, c.Int8)
	}
	return w
}
