name: Benchmarks
on:
  pull_request:
  workflow_dispatch:
    inputs:
      old:
        description: 'Old'
        required: false
        default: 'main'
      new:
        description: 'New'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  benchmark:
    name: benchmark (${{ matrix.name }})
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: min-version
            go-version: ''
            go-version-file: new/go.mod
          - name: latest-version
            go-version: stable
            go-version-file: ''
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.new }}
          path: new

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.old || github.event.pull_request.base.sha }}
          path: old

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          go-version-file: ${{ matrix.go-version-file }}
          check-latest: ${{ matrix.go-version == 'stable' }}
          cache-dependency-path: '*/go.sum'

      - name: Install benchstat
        run: go install golang.org/x/perf/cmd/benchstat@latest

      - name: Run benchmarks
        run: |
          mkdir results
          new/.github/workflows/benchmark.sh old new results

      - name: Compare benchmarks
        run: |
          EOF="$(dd if=/dev/urandom bs=15 count=1 status=none | base64)"
          {
            echo "RESULT<<$EOF"
            go version
            benchstat results/old results/new
            echo "$EOF"
          } >> "$GITHUB_ENV"

      - name: Comment benchmark result
        if: github.event_name == 'pull_request'
        continue-on-error: true
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: ${{ matrix.name }}
          hide_and_recreate: true
          hide_classify: "OUTDATED"
          message: |
            ```
            ${{ env.RESULT }}
            ```
