name: Tests

on:
  push:
    tags:
      - "*"
    branches:
      - main
  pull_request:
  merge_group:
    types: [checks_requested]

permissions:
  contents: read

# Cancel ongoing workflow runs if a new one is started
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Run actionlint
        shell: bash
        run: .github/workflows/lint-actions.sh
  lint-golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Run golangci-lint
        shell: bash
        run: .github/workflows/lint-golang.sh
  lint-go-mod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - shell: bash
        run: go mod tidy
      - shell: bash
        run: .github/workflows/check-clean-branch.sh
  lint-go-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - shell: bash
        run: go install ./canoto
      - shell: bash
        run: go generate ./...
      - shell: bash
        run: .github/workflows/check-clean-branch.sh
  tests-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - shell: bash
        run: go test -cover -race -shuffle=on ./...